spring:
  application:
    name: gateway-service
  cloud:
    nacos:
      server-addr: http://localhost:8848
    gateway:
      #      设置跨域访问
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: order-route
          uri: lb:http://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
server:
  port: 9000

---
spring:
  profiles: p9001
server:
  port: 9001
